### ISSUE TITLE
Try music-metadata-browser

### ISSUE THREAD

**Issue by Borewit** [soundsliceapp/prototype#22]
@ziir can you give [music-metadata-browser](https://github.com/Borewit/music-metadata-browser) a try? 
I would like to hear your feedback.

**Comment by ziir** [comment]
Hi @Borewit, thanks for the heads-up!
I am not sure how to use [music-metadata-browser](https://github.com/Borewit/music-metadata-browser) for [soundcut](https://github.com/soundcut/app)..

At the moment, my use-cases are:
- decode audio file data using [Base​Audio​Context​.decode​Audio​Data()](https://developer.mozilla.org/en-US/docs/Web/API/BaseAudioContext/decodeAudioData) as fast as possible, by [parsing mp3 file frames so I can decode multiple chunks in parallel.](https://github.com/soundcut/app/blob/master/shared/helpers/getFileAudioBuffer.js#L74-L140) 
- select chunks out of an audio file to create a new audio file that matches the user's selected start/end boundaries.

Both of these use-cases are handled with the use of [mp3-parser](https://github.com/biril/mp3-parser) which enables me to read the audio frames of an mp3 file.

You can try soundcut in its current beta state at https://www.soundcut.pw, I'd be happy to know if you have suggestions on how music-metadata-browser could be helpful in a project such as soundcut.

**Comment by Borewit** [comment]
I thought mp3-parser was used for extracting metadata, which is apperently not the case. Not sure how can add any value to project actually. I do have a MPEG frame parser embedded as well ofcourse, not designed to be called from API though. Unless you are intrested in the metatata, artists, track title, bitrate, encoding type etc, it may not be in your interest. In sound cutting app which could support multiple formats would be very intresting for me to have, but In know that is a massive amount of work.

**Comment by ziir** [comment]
Thanks for your answer.
It's possible that soundcut could make use of reading such metadata in the future, as well as writing it too.
I'm intrigued by your wish for soudcut to support multiple formats, would you like to tell me more so I can figure out feasibility and priority?

As a side note, I fear `music-metadata-browser` might be too big for me to include into soundcut in its current state - it's bigger than the full soundcut bundle at the moment.

**Comment by ziir** [comment]
I'm closing this, feel free to open other issues or message me directly :)

**Comment by Borewit** [comment]
I am interested to have an application, able to reduce the audio length and preserve the rest of the characteristics (keep metadata).

I receive sample audio sample files from users, and typically I turn then into a unit test. For copyright reasons it's better to get rid of most of the audio content. In addition to that it keeps the size of the project reasonable.

**Comment by ziir** [comment]
@Borewit It is quite trivial to implement #23 to cover your use case for most mp3 files.
Feel free to take a shot at it if you want to try :)
Otherwise, I'll tackle it some time in the next few days.
